apiVersion: v1
kind: Service
metadata:
  name: connectto-service
  namespace: devops-tools
spec:
  selector:
    app: jenkins-agent-connectto
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
