apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      containers:
      - name: ubuntu-container
        image: jenkins_agent/bullseye-lts:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
