apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "8.1.2" # Chart version
    values:
      global:
        hosts:
          domain: devops-gitlab.com # use a real domain here
        ingress:
          configureCertmanager: false
      certmanager-issuer:
        email: youremail@example.com # use your real email address here
