---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-operator
  namespace: devops-tools
  labels:
    app.kubernetes.io/name: jenkins-operator
    helm.sh/chart: jenkins-operator-0.8.0-beta.2
    app.kubernetes.io/version: "0.8.0-beta.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-operator
    spec:
      serviceAccountName: jenkins-operator
      containers:
        - name: jenkins-operator
          image: quay.io/jenkins-kubernetes-operator/operator:v0.8.0-beta2
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          command:
            - /manager
          args: []
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jenkins-operator"
          resources:
            limits:
              cpu: 100m
              memory: 120Mi
            requests:
              cpu: 100m
              memory: 120Mi