apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3-deployment
  namespace: devops-tools
  labels:
    app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      containers:
        - name: nexus3
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          resources:
            limits:
              cpu: 2000m
              memory: 8Gi
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus3-pv-new-claim