kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-nexus3-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus3-pv-new-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: nexus3-pv-new-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop # To be replace with presistent volume on VM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-pv-new-claim
  namespace: devops-tools
spec:
  storageClassName: local-nexus3-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi