apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  type: NodePort
  selector:
    app: nexus3
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32001
