apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: nexus3
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32001
