apiVersion: v1
kind: Service
metadata:
  name: samba-ad-service
  namespace: devops-tools
spec:
  type: LoadBalancer
  ports:
  - name: dns
    port: 53
    protocol: TCP
  - name: ldap
    port: 389
    protocol: TCP
  - port: 445
    name: smb
    protocol: TCP
  selector:
    app: samba-ad