apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-connectto-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-agent-connectto
  template:
    metadata:
      labels:
        app: jenkins-agent-connectto
    spec:
      containers:
      - name: ubuntu-container
        image: devops-tools/jenkins-connect:v1.4
        imagePullPolicy: IfNotPresent
