apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: devops-tools
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
    - protocol: TCP
      port: 1389
      targetPort: 1389
      nodePort: 32389
      name: ldap
    - protocol: TCP
      port: 1636
      targetPort: 1636
      nodePort: 32636
      name: ldaps