apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: devops-tools/openldap:v1.0.1
          ports:
            - containerPort: 1389
              name: ldap
            - containerPort: 1636
              name: ldaps
          volumeMounts:
            - name: data
              mountPath: /bitnami/openldap/data
      volumes:
        - name: data
          emptyDir: {}
