apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-pv
  namespace: devops-tools
spec:
  storageClassName: local-storage
  claimRef:
    name: samba-pv-claim
    namespace: devops-tools
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop # To be replace with presistent volume on VM
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
